### ISSUE TITLE
% and tags

### ISSUE THREAD

**Issue by marked** [ArchiveTeam/tumblr-grab#11]
```335246=404 http://konomary.tumblr.com/page/%0Atagged/%0Atagged/%0Atagged/tagged/%0Atagged/tagged/%0Atagged/tagged/tagged/tagged/tagged/%0Atagged/tagged/tagged/%0Atagged/tagged/ref```

%0A is LineFeed

**Comment by Arkiver2** [comment]
What issue is this referring to exactly?

**Comment by Arkiver2** [comment]
Regaring above, line https://github.com/ArchiveTeam/tumblr-grab/blob/master/tumblr.lua#L21 should be
```lua
local concat = "^https?://".. item_value .. "%.tumblr%.com/?[^/]*/?[^/]*/?[^/]*/?[^/]*/?[^/]*$"
```

**Comment by Arkiver2** [comment]
Fixed with https://github.com/ArchiveTeam/tumblr-grab/commit/d185fd57d90c11186670660415b9d82be7d84902.

**Comment by Arkiver2** [comment]
To note, this was not an issue with percent encoding or (percent encoded) newlines. This was an issue with not detecting the number of `/` occurences due to the use of `.*` instead of `[^/]*`.
