### ISSUE TITLE
PR/Patches have no support for test environment

### ISSUE THREAD

**Issue by marked** [ArchiveTeam/tumblr-grab#15]
PR's  for patches should ideally be tested first but scripts do not support testing environment without modification by hand.

**Comment by kiska3** [comment]
You can modify: https://github.com/ArchiveTeam/tumblr-grab/blob/master/pipeline.py#L64

And test using server5.kiska.pw:9080 and import using admin url, then queue tasks as tumblr-blog:<blog name>

Unfortunately I have gotten use to modifying that line enough that I don't mind.

**Comment by marked** [comment]
I'm more concerned about those testing changes, besides us, need to be kept off the production tracker.  I'll write up some options.

**Comment by km09** [comment]
https://git-scm.com/docs/git-branch
