### ISSUE TITLE
URLs for embed currently in crawl

### ISSUE THREAD

**Issue by marked** [ArchiveTeam/tumblr-grab#3]
These links in the current crawl only have json, meant for an embeding UI workflow
https://www.tumblr.com/oembed/1.0?url=http://ladycynthiana.tumblr.com/post/180925803503
https://www.tumblr.com/oembed/1.0?url=http://cocchino.tumblr.com/post/123103513327/eberhardtsmith-mrzyk-moriceau-made-this

**Comment by Arkiver2** [comment]
Can you please provide some more information as to why this is a problem? I'm missing the context here.

**Comment by marked** [comment]
The crawl might be slow because lots of small requests.  If this one is not needed for rendering the archive we're just wasting time grabbing it.  I'm not sure if it's needed until it's excluded from a .warc and viewed, but it would be reasonable to expect t's not needed.

**Comment by marked** [comment]
Another incoming report
http://sarathemaiden.tumblr.com/post/119513476681/embed

**Comment by marked** [comment]
Fixed in Pull Request #21

**Comment by marked** [comment]
After consultation, oembed is use for embeding a post into other websites.
This has been nixed.

/embed is a UI for getting HTML code for  embedding, this has been left in for now at the request of a user.

**Comment by Arkiver2** [comment]
I'm assuming this issue is not an issue anymore since it was decided to not block notes?

**Comment by marked** [comment]
IRC consensus was to block /embed
and keep /likes

/embed is the UI for generating HTML embed snippets.
