### ISSUE TITLE
templated URL's are in crawl   :id  :year  :month  :page

### ISSUE THREAD

**Issue by marked** [ArchiveTeam/tumblr-grab#37]
http://blackberrymessengerpins.tumblr.com/archive/:year/:month?before_time=1358791255

http://ohlarryohlouisohharry.tumblr.com/.:blog_not_found

.tumblr.com/post/:id

WARC-Target-URI: https://fluffy-wolf-strife.tumblr.com/post/:id/embed
WARC-Target-URI: https://fluffy-wolf-strife.tumblr.com/post/:id/embed
WARC-Target-URI: https://fluffy-wolf-strife.tumblr.com/post/:id/
WARC-Target-URI: https://fluffy-wolf-strife.tumblr.com/post/:id/

54=200 https://fluffy-wolf-strife.tumblr.com/page/:page

**Comment by Fusl** [comment]
Fixed in #66
