### ISSUE TITLE
Googlebot UA makes our requests low-priority

### ISSUE THREAD

**Issue by drdaxxy** [ArchiveTeam/tumblr-grab#42]
As in https://github.com/ArchiveTeam/tumblr-grab/issues/2#issuecomment-447230002, I tested crawling with a desktop browser UA and session/GDPR cookies.

Tumblr seems to give spiders significantly lower priority than real browsers when serving dynamic requests. Requests that fairly consistently complete in 300ms with Chrome's UA can take anything between that and over 5 seconds with Googlebot's.

Crawling `staff.tumblr.com` for 10 minutes with master pipeline.py yielded for me: 37 MB data directory, 342 URL fetches, <700kbit/s average download.
10 minutes with Chrome UA and session and GDPR cookie: 187 MB data directory, 1349 URL fetches, 3.5 mbit/s average download.

As mentioned in #2 the crawled URLs don't line up exactly. Not sure why. Full logs:
[staff_crawl_10min_googlebot.txt](https://github.com/ArchiveTeam/tumblr-grab/files/2678924/staff_crawl_10min_googlebot.txt)
[staff_crawl_10min_chrome_loggedin.txt](https://github.com/ArchiveTeam/tumblr-grab/files/2678923/staff_crawl_10min_chrome_loggedin.txt)

I also tested 11 random blogs that happened to scroll by on my production warriors, concurrently, on one otherwise idle, mediocre dedicated server (old low-end quadcore Xeon, rotational HDDs, hardware RAID1 but on a terrible controller, 1gbps switch port but mass hoster). Yielded 2.6 GB data directory, who knows how many fetches, and something between 35 and 50 mbit/s average download.

**Comment by drdaxxy** [comment]
Here's the response diff for Googlebot vs. Chrome on staff.tumblr.com: https://gist.github.com/drdaxxy/2d24fa07af036a3383a7cf4927cb6fc9

And for https://staff.tumblr.com/post/172170432865/were-taking-steps-to-protect-against-future: https://gist.github.com/drdaxxy/c007dc8c73d6d0a01ef00b9726bbd8b5

Note, the Chrome response is almost 100kB longer, and it's all in additional "related posts" data. This seems to be the cause of the crawl differences.

**Comment by marked** [comment]
Thought about this more, there's a slight risk that the extra 100kB could add more URLs to the job and spiral but the answer is just test them side by side and see if the URLs included in a final WARC increases.

**Comment by barzamin** [comment]
@marked i agree; which other patches decrease footprint though?

**Comment by marked** [comment]
Deduping or postponing the images.  I believe the highest % of bytes is media, but I'll run another report.
