### ISSUE TITLE
"Project code is out of date"

### ISSUE THREAD

**Issue by raingloom** [ArchiveTeam/tumblr-grab#47]
`Project code is out of date and needs to be upgraded. To remedy this problem immediately, you may reboot your warrior. Retrying after 70 seconds...`

i rebooted my container several times, still getting this error

tried rm-ing and running the image again, same thing happens

**Comment by scrottie** [comment]
People are working on throttling things so that they don't get banned, then there will be that new version.  In the mean time, people are using other tools to scrape Tumblr.

**Comment by scrottie** [comment]
The tracker maintainer will bump the required version number before that new version is available or even the strategy for it decided on, just as a way of closing the queue.  Messages between tracker and the warrior could definitely be improved.  A "please stand by while we adjust" message would be very welcome.
